### ISSUE TITLE
Traceback (most recent call last):   File "main.py", line 87, in <module>     main()   File "main.py", line 63, in main     inp_model_path = convert_model(org_model_path, in_version)   File "main.py", line 81, in convert_model     meta_utils.run_docker(docker_image, command, verbose)   File "/home/ayushman/Documents/python/DeepLearning/keras-video-classification/tensorflow-model-converter/utils/meta_utils.py", line 26, in run_docker     subprocess.run(args.split(), check=True, capture_output=not verbose)   File "/usr/lib/python3.7/subprocess.py", line 512, in run     output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['docker', 'run', '-it', '--rm', '--name', 'convert-tf', '-v', '/home/ayushman/Documents/python/DeepLearning/keras-video-classification/tensorflow-model-converter:/convert', '-w', '/convert', 'tensorflow/tensorflow:1.15.0-py3', 'python', 'convert_model.py', '-m', 'keras_model.h5', '-o', 'output_models/keras_model_tensorflow_1_15_0']' returned non-zero exit status 126.

### ISSUE THREAD

**Issue by ayushmankumar7** [OlofHarrysson/tensorflow-model-converter#1]
![Screenshot from 2020-01-29 22-09-53](https://user-images.githubusercontent.com/41910134/73376859-1fb2a700-42e4-11ea-8b33-21444665d767.png)

**Comment by OlofHarrysson** [comment]
Hi, if you update the repo, (do a git pull) and run the command again it will print some outputs. I had forgotten to enable print docker output by default.

What kind of model are you trying to convert? I'd be glad to help out

**Comment by OlofHarrysson** [comment]
Uh... I guess that wasn't in for the conversion of the model. I'll put it into master - just changing `def convert_model(model_path, tf_version, verbose=False):` to `def convert_model(model_path, tf_version, verbose=True):`

**Comment by ayushmankumar7** [comment]
h5

**Comment by OlofHarrysson** [comment]
> h5

What? 😅 Did you manage to figure out the problem? I'm interested in knowing
