### ISSUE TITLE
Unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by rai-harshit** [OlofHarrysson/tensorflow-model-converter#2]
Not sure if this error is because of the code or because of docker because I've not really used docker before, so I'm not sure what exactly went wrong here. Help would be really appreciated. Thanks !

```
(intel_nlp) C:\Users\harsh\Desktop\dtoxd-demo\server\tensorflow-model-converter>python main.py -m ..\5C_model.h5 -i 1.15.0 -o 1.14.0
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 64, in main
    inp_model_path = convert_model(org_model_path, in_version, verbose)
  File "main.py", line 82, in convert_model
    meta_utils.run_docker(docker_image, command, verbose)
  File "C:\Users\harsh\Desktop\dtoxd-demo\server\tensorflow-model-converter\utils\meta_utils.py", line 26, in run_docker
    subprocess.run(args.split(), check=True, capture_output=not verbose)
  File "C:\Users\harsh\Anaconda3\envs\intel_nlp\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by OlofHarrysson** [comment]
Hi, I believe that this is due to a miss-match in the python version. I'm using the python module [subprocess](https://docs.python.org/3.6/library/subprocess.html) to execute bash commands, and it seems that a keyword argument (capture_output) that I was using is only available since Python 3.7. 

I'll confirm by trying to run the code in Python 3.6, and update the README if that's the case.

If you don't mind me asking. What kind of model are you trying to convert? From which version and what is the desired version?

**Comment by rai-harshit** [comment]
Thanks a lot for your lightning fast reply. If that is the case, I'll try to run it on Python 3.7 as well. Python version is not really a big deal for me right now, but getting that model converted is important.

I've a Mobilenet V2 model which was built using TF1.15 (an it contains ragged tensor) and I'm trying to get it working for TF1.14.

I am working on an application for which I'll need to bundle this whole thing into an executable and I'm using PyInstaller for that. Apparently, PyInstaller doesn't yet support TF1.15. So, the only option I have is to try to backport my code, at least for now.

**Comment by OlofHarrysson** [comment]
Np, I'm glad to help :) The repo is only tested on a few models but I think it should handle a Mobilenet v2. The way I handle ragged tensors is just to recursively delete them before loading the model.

There are some kinks as I haven't spent that much time on the repo. I fixed a glaring error just now, so feel free to pull from master again. Shoot me a message if things aren't working properly

**Comment by rai-harshit** [comment]
Sure, thanks a lot for your support. I will try this with Python 3.7 and will get back to you in case anything else goes wrong. I'll close the issue once I confirm that it works. Cheers !

**Comment by rai-harshit** [comment]
Running it with Py3.7 solved the earlier issue, but ended up with the following one. This is the docker output. I'm running Windows 10 + Python 3.7.4 (Anaconda Distrinution).

```
Traceback (most recent call last):
  File "/convert/utils/tf_utils.py", line 29, in load_model
    return keras.models.load_model(path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 212, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 352, in from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py", line 352, in from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1121, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1105, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 446, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_layer.py", line 80, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert_model.py", line 35, in <module>
    main()
  File "convert_model.py", line 28, in main
    model = tf_utils.load_model(model_path)
  File "/convert/utils/tf_utils.py", line 31, in load_model
    return _load_json_model(path)
  File "/convert/utils/tf_utils.py", line 48, in _load_json_model
    model.load_weights(path_weights)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 749, in load_weights_from_hdf5_group
    layer, weight_values, original_keras_version, original_backend)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 374, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 362, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 374, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 350, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 456, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 65, in main
    out_model_path = convert_model(inp_model_path, out_version, verbose)
  File "main.py", line 82, in convert_model
    meta_utils.run_docker(docker_image, command, verbose)
  File "C:\Users\harsh\Desktop\dtoxd-demo\server\tensorflow-model-converter\utils\meta_utils.py", line 26, in run_docker    subprocess.run(args.split(), check=True, capture_output=not verbose)
  File "C:\Users\harsh\Anaconda3\envs\py37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'run', '-it', '--rm', '--name', 'convert-tf', '-v', 'C:\\Users\\harsh\\Desktop\\dtoxd-demo\\server\\tensorflow-model-converter:/convert', '-w', '/convert', 'tensorflow/tensorflow:1.14.0-py3', 'python', 'convert_model.py', '-m', 'output_models\\5C_model_tensorflow_1_15_0\\5C_model.h5', '-o', 'output_models\\5C_model_tensorflow_1_14_0']' returned non-zero exit status 1.

```

**Comment by OlofHarrysson** [comment]
Hmm, I don't know what causes that :/ A google search suggests that there could be a few things that can cause this. Could you send me the model and I'll also try to get it converted? :)

**Comment by rai-harshit** [comment]
Yeah sure, I'll send that over to you. Sending it on your email.

**Comment by rai-harshit** [comment]
Just sent it on your email. Please check. Do let me know what happens. Thanks !

**Comment by rai-harshit** [comment]
Seems like some issue with the nested model. I'll try to solve it. Meanwhile, do let me know in case you find anything on this.
Cheers !

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\engine\training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 749, in load_weights_from_hdf5_group
    layer, weight_values, original_keras_version, original_backend)
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 374, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 362, in convert_nested_model
    original_backend=original_backend))
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 374, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 350, in convert_nested_model
    original_backend=original_backend))
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 456, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\numpy\core\fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "C:\Users\harsh\Anaconda3\envs\tf14\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
```

**Comment by OlofHarrysson** [comment]
I helped Stan convert his model the day after - the updates needed are in master now :) Closing issue
